#   __                            __                  
#  /  |                          /    /               
# |___|      ___  ___  ___  ___ (___    ___  ___  ___ 
# |   )|   )|   )|   )|___)|___)    )| |   )|   )|___ 
# |__/ |__/ |  / |__/ |__  |__   __/ | |__/ |  /  __/ 
#                __/                   __/            
#
# BungeeSigns Version 2.1 Release
# http://www.codebucket.de/plugins/BungeeSigns
# ------------------------------------------------------------------------

options:
  logConsole: true
  use-cooldown: 5
  sign-updates: 100
  ping-interval: 5
  connect-timeout: 4000

servers:
  pvp:
    address: '127.0.0.1:25566'
    displayname: '&cPVP'
  survival:
    address: '127.0.0.1:25567'
    displayname: '&aSurvival'