#   __                            __                  
#  /  |                          /    /               
# |___|      ___  ___  ___  ___ (___    ___  ___  ___ 
# |   )|   )|   )|   )|___)|___)    )| |   )|   )|___ 
# |__/ |__/ |  / |__/ |__  |__   __/ | |__/ |  /  __/ 
#                __/                   __/            
#
# BungeeSigns Version 1.3 Release
# http://www.codebucket.de/plugins/BungeeSigns
# ------------------------------------------------------------------------

logConsole: true

interval: 5
timeout: 4000
cooldown: 5

servers:
  pvp:
    address: '127.0.0.1:25566'
    displayname: '&cPVP'
  survival:
    address: '127.0.0.1:25567'
    displayname: '&aSurvival'