name: BungeeSigns
author: Codebucket
version: 1.8 Release
main: de.codebucket.bungeesigns.BungeeSigns
website: http://www.codebucket.de
commands:
     bsreload:
          description: Reloads the plugin.
          usage: /<command>